name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake with Coverage
      run: >
        cmake -S . -B build 
        -DCMAKE_BUILD_TYPE=Debug 
        -DCMAKE_CXX_FLAGS="--coverage -O0" 
        -DCMAKE_EXE_LINKER_FLAGS="--coverage"

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ./build/matrix_test

    - name: Install gcovr
      run: sudo apt-get update && sudo apt-get install -y gcovr

    - name: Generate Coverage Report
      run: gcovr -r . --xml -o coverage.xml --exclude="test/.*" --exclude="src/main.cpp"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
