name: Code Linters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      # This creates the build directory (-B) and points to the source root (-S)
      run: cmake -S . -B build

    - name: Build
      # This compiles the code inside the newly created build directory
      run: cmake --build build

    - name: Run C/C++ Linter
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: 'file'
        tidy-checks: ''
        thread-comments: 'update'

    - name: Fail pipeline if linting fails
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1
